### ISSUE TITLE
Azure Container Instance Port Issue

### ISSUE THREAD

**Issue by metamultiverse** [linuxserver/docker-blender#4]
Hi Team,
I can run the container in browser for my local host with 3000 port but when I tried to run it in Azure Container Instance with 3000 port enabled. It doesnt load with http://IP:3000
Azure Container Instance does not support port mapping. What could be other solution to run it over the cloud.

Thanks

**Comment by j0nnymoe** [comment]
We don't test/use/support our containers on Azure's container platform.
